DROP TABLE IF EXISTS PRODUCT_ARTICLE;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS ARTICLE;

CREATE TABLE ARTICLE
(
    ARTICLE_ID      BIGINT PRIMARY KEY,
    NAME            VARCHAR NOT NULL,
    AVAILABLE_STOCK INT     NOT NULL
--     PRODUCT_ID      BIGINT AUTO_INCREMENT NOT NULL,
--     FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID)
);

CREATE TABLE PRODUCT
(
    PRODUCT_ID BIGINT AUTO_INCREMENT NOT NULL,
    NAME       VARCHAR               NOT NULL,
    PRICE      DECIMAL
--     ARTICLE_ID BIGINT,
--     FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE (ARTICLE_ID)
);

CREATE TABLE PRODUCT_ARTICLE
(
    PRODUCT_ID BIGINT NOT NULL,
    ARTICLE_ID BIGINT NOT NULL,
    QUANTITY   INT    NOT NULL,
    PRIMARY KEY (PRODUCT_ID, ARTICLE_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID),
    FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE (ARTICLE_ID)
);
